stages:
  - build
  - package
  - notify

variables:
  DEBIAN_FRONTEND: 'noninteractive'
  COMPOSER_ALLOW_SUPERUSER: 1
  COMPOSER_CACHE_DIR: "$CI_PROJECT_DIR/.cache/composer"
  NPM_CONFIG_CACHE: "$CI_PROJECT_DIR/.cache/npm"
  CI_BUILD_DIR: '/tmp/plugin'
  MOODLE_BRANCH: 'MOODLE_403_STABLE'
  MOODLE_BEHAT_WWWROOT: 'http://localhost:8000'
  MOODLE_BEHAT_WDHOST: 'http://behat:4444/wd/hub'
  MOODLE_START_BEHAT_SERVERS: 'no'
  DB: 'mariadb'

build:snapshot:
  stage: build
  image: moodlehq/moodle-php-apache:7.4
  tags:
    - co-legacy-docker
  services:
    - name: selenium/standalone-chrome:3
      alias: behat
    - name: mariadb:10.6
      alias: db
      command:
        - '--character-set-server=utf8mb4'
        - '--collation-server=utf8mb4_unicode_ci'
        - '--innodb_file_per_table=On'
        - '--wait-timeout=28800'
        - '--skip-log-bin'
      variables:
        MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
  cache:
    paths:
      - .cache
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  variables:

  before_script:
    # replacing version number in version.php
    - export VERSION=$(echo $(git show -s --format=%cd --date=short $CI_COMMIT_SHA | sed 's/-//g')00)
    - sed -i 's/\(\$plugin->version = \)[0-9]\+;/\1your_new_number_here;/' version.php
    - mkdir -pv "$CI_BUILD_DIR"
    - cp -ru "$CI_PROJECT_DIR/"* "$CI_BUILD_DIR"
    - mkdir -p /usr/share/man/man1 /usr/share/man/man3 /usr/share/man/man7
    - apt-get -qq update
    - apt-get -yqq install --no-install-suggests default-jre-headless mariadb-client
    - 'curl -sS https://raw.githubusercontent.com/creationix/nvm/v0.39.3/install.sh | bash'
    - . ~/.bashrc
    - nvm install --default --latest-npm lts/gallium
    - 'curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer'
    - composer create-project -n --no-dev --no-progress --no-ansi moodlehq/moodle-plugin-ci /opt/mci ^3
    - export PATH="/opt/mci/bin:/opt/mci/vendor/bin:$PATH"
    - moodle-plugin-ci install --db-host db
    - '{ php -S 0.0.0.0:8000 -t "$CI_PROJECT_DIR/moodle" >/dev/null 2>&1 & }'
  script:
    - moodle-plugin-ci phplint
    - moodle-plugin-ci phpunit
    - moodle-plugin-ci behat --auto-rerun 0 --profile chrome
  artifacts:
    paths:
      - "$CI_BUILD_DIR/*"

package:snapshot:
  image:
    name: gcr.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: [ "" ]
  stage: package
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - co-cloud
  script:
    - echo "{\"auths\":{\"registry.campusonline.cloud\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - cat "$CI_BUILD_DIR/version.php" | grep -oP '(?<=version = ).*?(?=;)' > target/version
    - APPVERSION="$(cat target/version)"
    - /kaniko/executor
      --context "${CI_BUILD_DIR}/"
      --dockerfile "${CI_BUILD_DIR}/updater.Dockerfile"
      --destination "registry.campusonline.cloud/campusonline/campusonline-moodle-plugin-updater:${APPVERSION}"
  needs:
    - job: build:snapshot
  artifacts:
    paths:
      - target/version

notify:snapshot:
  image: alpine:latest
  stage: notify
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  tags:
    - co-cloud
  before_script:
    - apk add curl
  script:
    - VERSION="$(cat target/version)"
    - curl -X POST -F token=$CI_CO_APPS_TRIGGER_TOKEN -F ref=snapshot \
        --form variables[APP]="moodle" \
        --form variables[VERSION]="$VERSION" \
        "https://gitlab.campusonline.community/api/v4/projects/6/trigger/pipeline"
  needs:
    - job: package:snapshot
